### ISSUE TITLE
Upstox Auto login - 403 error in POST method after 302

### ISSUE THREAD

**Issue by SANTHAKUMAR09** [Indian-Algorithmic-Trading-Community/Upstox#2]
403 error in POST method after 302 for next request

line no: 109 
  response = await client.post(
                        routes["otp_generate"],
                        json=otp_data, 
                        params={
                                "requestId" : f"WPRO-{generateUniqueID()}"
                                }
                        )

**Comment by Tapanhaz** [comment]
Upstox updated its service endpoint and some header parameters. Code is updated to match with the changes. Please check now.

**Comment by Tapanhaz** [comment]
I am going to close this issue now. If there is any proble please open a new issue.
